### ISSUE TITLE
Comparison function API specification

### ISSUE THREAD

**Issue by nsheff** [ga4gh/seqcol-spec#21]
We earlier discussed the compatibility function  #7 , which was focused on my original idea of the flag system. We've moved away from that approach to a more verbose return result. We've also moved toward having a single endpoint that accepts a POST, which can provide multiple options for sequence collection expansion levels. We will track the new approach in this issue.

## How will the comparison function API be specified?

We must define 3 components:

1. endpoint name
2. Structure of POST content provided by user
3. Structure of value returned by server.

## 1. Endpoint name

Proposal: `/compare`, and it's a `POST` endpoint.

## 2. Structure of POST content provided by user

The user posts an object with two properties, `seqcolA` and `seqcolB`:

```
{ "seqcolA": ...,
  "seqcolB": ... }
```
The values of either entry must be in one of 3 forms: level 0: a string digest; level 1: an object with named string digests; or level 2:  an object with named arrays.

### Level 0 digests

This example shows a comparison of 2 digests:

```
{ 
  "seqcolA": "a6748aa0f6a1e165f871dbed5e54ba62",
  "seqcolB": "3b379221b4d6ea26da26cec571e5911c" 
}
```

### Level 1 digests

```
{ 
  "seqcolA": { 
    "lengths":"4925cdbd780a71e332d13145141863c1", 
    "names":"ce04be1226e56f48da55b6c130d45b94", 
    "sequences":"3b379221b4d6ea26da26cec571e5911c"
  }, 
  "seqcolB": {
    "lengths":"4925cdbd780a71e332d13145141863c1",
    "names":"ce04be1226e56f48da55b6c130d45b94",
    "sequences":"3b379221b4d6ea26da26cec571e5911c",
    "topologies":"1be4f869c6f754a9b0a379f5c2aa4ff9"
  }
}
```

### Level 2 objects

```
{ 
  "seqcolA": {
    "lengths": [
      "1216",
      "970",
      "1788"
    ],
    "names": [
      "A",
      "B",
      "C"
    ],
    "sequences": [
      "76f9f3315fa4b831e93c36cd88196480",
      "d5171e863a3d8f832f0559235987b1e5",
      "b9b1baaa7abf206f6b70cf31654172db"
    ]
  }, 
  "seqcolB": {
    "lengths": [
      "1216",
      "970",
      "1788"
    ],
    "names": [
      "A",
      "B",
      "C"
    ],
    "sequences": [
      "76f9f3315fa4b831e93c36cd88196480",
      "d5171e863a3d8f832f0559235987b1e5",
      "b9b1baaa7abf206f6b70cf31654172db"
    ],
    "topologies": [
      "linear",
      "linear",
      "linear"
    ]
  }
}
```

Any of these may also be mix-and-matched, so you can compare a level 0 digest to a level 2 object.

## 3. Structure of value returned by server

What does the return value from the API look like? Current proposal example:

```
{
  "lengths": {
    "any-elements-shared": true,
    "all-a-in-b": true,
    "all-b-in-a": true,
    "order-match": true,
  },
  "names": {
    "any-elements-shared": true,
    "all-a-in-b": true,
    "all-b-in-a": true,
    "order-match": true,
  },
  "sequences": {
    "any-elements-shared": false,
    "all-a-in-b": false,
    "all-b-in-a": false,
    "order-match": false,
  }
}
```

**Comment by tcezard** [comment]
### 1. GET vs POST
I tend to prefer to have only one way of doing things which is why I thought having both GET and POST seems unnecessary.  We have to remember that the specification is here to instruct the implementers on what is minimally required to be compatible with seqCol. Adding alias endpoints for any "simplified" use case is going to expand the complexity of the specs for very little gain and should therefore be avoided.
This said if we decide that the use case of comparing two seqCols is the only one we want to support then it makes sense to use GET for that.

### 2. `a, b` vs `first, second`
For this I don't have a strong preference as long as they are clearly specified in the query:
These query contents would be fine 
```
{ 
  "seqcolA": "a6748aa0f6a1e165f871dbed5e54ba62",
  "seqcolB": "3b379221b4d6ea26da26cec571e5911c" 
}
{ 
  "first": "a6748aa0f6a1e165f871dbed5e54ba62",
  "second": "3b379221b4d6ea26da26cec571e5911c" 
}
 ```
But I'm not a big fan of this one
```
[ 
  "a6748aa0f6a1e165f871dbed5e54ba62",
  "3b379221b4d6ea26da26cec571e5911c" 
]
```
Because I prefer clearly specifying the property names. But maybe this is the conclusion you guys reach already.

### 3. Availability at level 2
I must say I a bit puzzle by the idea that we should be worried that user would "use" the service. In my mind we either offer the server side comparison function or we don't. 
If we offer it for a query of `level 0` vs `level 0` then why not offering it on `level 0` vs `level 2` since `level 0` needs to be retrieved. And from there I don't see why not offering it for `level 2` vs `level 2`.
We could, of course, decide not to offer it server side and provide some code that can be run client side. In that case seqCol retain its original purpose of retrieval of the seqCol definition.
As for the concern of abuse of the service there are enough method out there (rate limit, throttling) to counter them that does not change the API design.

**Comment by nsheff** [comment]
Regarding structure of the return value, in the meeting on 2021-11-03, we discussed the possibility of inverting the structure. The example would look like this if inverted:

```
{
  "any-elements-shared": ["lengths", "names"]
  "all-a-in-b": ["lengths", "names"]
  "all-b-in-a": ["lengths", "names"]
  "order-match": ["lengths", "names"]
}
```
Instead of this:

```
{
  "lengths": {
    "any-elements-shared": true,
    "all-a-in-b": true,
    "all-b-in-a": true,
    "order-match": true,
  },
  "names": {
    "any-elements-shared": true,
    "all-a-in-b": true,
    "all-b-in-a": true,
    "order-match": true,
  },
  "sequences": {
    "any-elements-shared": false,
    "all-a-in-b": false,
    "all-b-in-a": false,
    "order-match": false,
  }
}
```

The inverted structure is much more concise, so I kind of like it for that reason, though it won't be quite as easy to navigate on the recipient end. The only question I have is, should there be a 5th element for "none" and, if so, what should it be called? It could either be implied that an attribute in none of the 4 arrays has no overlap, or we could make it explicit with a "no-overlap" array.

**Comment by sveinugu** [comment]
> The inverted structure is much more concise, so I kind of like it for that reason, though it won't be quite as easy to navigate on the recipient end. The only question I have is, should there be a 5th element for "none" and, if so, what should it be called? It could either be implied that an attribute in none of the 4 arrays has no overlap, or we could make it explicit with a "no-overlap" array.

My two cents is that we should definitely add an `no-overlaps` array with the rest of the arrays for the simple reason that it is cumbersome to have to check each digest separately to see which arrays are there. 

One question, though: What about arrays that are only present in one of the seqcols? There is a big difference between "array x is present in both a and b but with no overlapping items" and "array x is present only in a", but I believe both these scenarios would warrant the inclusion of the array in a `no-overlaps` result category. Should we add `only-in-a` and `only-in-b` arrays also?

**Comment by sveinugu** [comment]
BTW: I do like the inverted structure!

**Comment by nsheff** [comment]
Complete example:

```
{
  "any-elements-shared": ["lengths", "names"],
  "all-a-in-b": ["lengths", "names"],
  "all-b-in-a": ["lengths", "names"],
  "order-match": ["lengths", "names"],
  "no-overlap": ["sequences"],
  "only-in-a": [],
  "only-in-b": []
}
```

**Comment by nsheff** [comment]
Ok, since people weren't convinced on the comparison demos, I rewrote the function to show counts. Here's what it looks like now. This is the comparison of primary vs toplevel from ensembl:

```
{
  "a-in-b": {
    "lengths": 199,
    "names": 194,
    "sequences": 194
  },
  "b-in-a": {
    "lengths": 194,
    "names": 194,
    "sequences": 194
  },
  "a-total": {
    "lengths": 639,
    "names": 639,
    "sequences": 639
  },
  "b-total": {
    "lengths": 194,
    "names": 194,
    "sequences": 194
  },
  "a-duplicated": {
    "lengths": 10,
    "names": 0,
    "sequences": 0
  },
  "b-duplicated": {
    "lengths": 2,
    "names": 0,
    "sequences": 0
  },
  "order-match": [
    "lengths",
    "names",
    "sequences"
  ],
  "only-in-a": [],
  "only-in-b": []
}
```

You can see it in action now here: http://seqcolapi.databio.org/comparison/1c8acace4fc30133e7c3322f2bca45e0/6e8e6adc1b11c0ef4b6550ce6a84e144

This is definitely returning more information, so you can make a bit more detailed comparisons -- but it also requires a bit of processing to get at the result. For example in the case above, because `b-in-a` has 194 across the board, and the `b-total` is also 194, we can conclude that `b` is a proper subset of `a`.

**Comment by nsheff** [comment]
We reached a final decision for this and the ADR was approved: https://github.com/ga4gh/seqcol-spec/pull/22
