### ISSUE TITLE
Accepted/Recommended Sequence digest algorithms

### ISSUE THREAD

**Issue by tcezard** [ga4gh/seqcol-spec#30]
What are the accepted digests to represent sequence. Refget is not prescriptive about the digest that can be used which means there are as many digests for one sequence as there are digest algorithm.
In order to avoid getting too many SeqCol digest the specification will have to limit the digests that can be used to specify sequences.
We could specify only one accepted sequence digest algorithm.
We could have a list of recommended sequence digest algorithms.

**Comment by nsheff** [comment]
I think this is the same point that was raised previously in #6, which we have not yet solved. So, now is probably a good time to finalize this.

**Comment by tcezard** [comment]
Closed as duplicates
