### ISSUE TITLE
Reserved namespace policy for future extension of SeqCol

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/seqcol-spec#47]
One comment that came up during the Connect meeting that I thought was really interesting was the idea of conventions for a reserved array namespace in SeqCol. The idea being that if future properties are identified that would become part of the specification, it would provide a mechanism for adding those properties without potentially colliding with implementation-defined array names. An idea proposed was that a case-sensitive convention could be used for this purpose, which may have implications for #33.

**Comment by nsheff** [comment]
We made a decision on this, which is outlined in this ADR:

https://github.com/ga4gh/seqcol-spec/pull/49
