### ISSUE TITLE
Identifier vs digest in the specs

### ISSUE THREAD

**Issue by sveinugu** [ga4gh/seqcol-spec#60]
In the specification, the words "identifier" vs "digest" are used interchangeably - I have at least not noticed any patterns. I believe we decided to only talk about digests for now and wait with talking about identifiers until we (or someone else) solved the namespacing. That might have just been my opinion though, and not something we agreed on...

**Comment by nsheff** [comment]
Good point. I think I have been using them interchangeably. Sometimes they are interchangeable, but sometimes they are not, so I finally went through and looked at this. I changed a lot of 'identifier' to 'digest' because it seemed a better fit. 

Thanks for raising this

**Comment by nsheff** [comment]
If you see other instances you think should change, please do so.
