### ISSUE TITLE
Documentation request- seqcol without sequences

### ISSUE THREAD

**Issue by mikelove** [ga4gh/seqcol-spec#73]
Can you provide an example of canonical seqcol object representation when sequences are not provided, as in [F4](https://seqcol.readthedocs.io/en/latest/specification/#f4-sequence-collections-without-sequences).

Do you leave off the `sequences` entry or do you digest the empty string or other?

@rob-p

**Comment by nsheff** [comment]
Ok, I'll add that. basically you just don't include the sequences attribute at all. (no digested empty string)

**Comment by nsheff** [comment]
I added an example to the spec:

```
{
  "lengths": [
    "1216",
    "970",
    "1788"
  ],
  "names": [
    "A",
    "B",
    "C"
  ]
}
```
